
name: $(Date:yyyyMMdd)$(Rev:-rr)

resources:
  repositories:
    - repository: templates
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.package-signing.2.0.6
      endpoint: UiPath

variables:
- template: .pipelines/vars.yml

stages:
- stage: BuildAndTest
  jobs:
      - job: Test
        workspace:
          clean: all
        displayName: "Test"
        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: AzureSigningInternalProductionEA
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              workingDirectory: "$(Build.Repository.LocalPath)"
              scriptType: bash
              inlineScript: |
                az --version
                az account show